version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 54321:5432

  seed:
    build: ./setup/db
    depends_on:
      - db
    links:
      - db
